### ISSUE TITLE
Game crashes before fully starting up.

### ISSUE THREAD

**Issue by Zarepheth** [jredfox/evilnotchlib#30]
### Versions: 
- **MultiMC 5**: 0.6.2-1222
- **Minecraft**: 1.12.2
- **Forge**: 14.23.4.2760
- **EvilNotchLib**: 1.2.02

### Issue:
During game startup, the game starts loading resources and processing, then abruptly stops about 20-30 seconds after starting.

### Steps to reproduce:
1. Install all the mods (it's a big list...)
2. Attempt to run the game.

### CrashReport/Log:
Full Log: [https://paste.ee/p/5qYGb](https://paste.ee/p/5qYGb)

**Errors**:
```
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: java.lang.reflect.InvocationTargetException
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launch:231]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: Caused by: java.lang.NoClassDefFoundError: com/EvilNotch/lib/util/JavaUtil
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at com.EvilNotch.silkspawners.asm.SilkTransformer.<clinit>(SilkTransformer.java:18)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.<init>(ASMTransformerWrapper.java:243)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at $wrapper.com.EvilNotch.silkspawners.asm.SilkTransformer.<init>(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at java.lang.Class.newInstance(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.LaunchClassLoader.registerTransformer(LaunchClassLoader.java:88)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper.injectIntoClassLoader(CoreModManager.java:131)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[19:08:25] [main/INFO] [STDERR]: [org.multimc.onesix.OneSixLauncher:launchWithMainClass:200]: 	... 8 more
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: com.EvilNotch.lib.util.JavaUtil
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 25 more
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[19:08:25] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 27 more
[19:08:25] [main/INFO] [STDOUT]: [org.multimc.EntryPoint:main:37]: Exiting with -1
```

### ModPack/ModList: 

Github has no markdown for spoilers or collapsing regions? I've got a list of 202 mods. However, they are all listed near the beginning of the already referenced [log file](https://paste.ee/p/5qYGb).

**Comment by jredfox** [comment]
use latest evil notch lib
