### ISSUE TITLE
Can't start Magma server with Evil Notch Lib

### ISSUE THREAD

**Issue by 233Neon** [jredfox/evilnotchlib#83]
java.lang.NullPointerException
        at com.evilnotch.lib.asm.transformer.EntityTransformer.patchPlayer(EntityTransformer.java:257)
        at com.evilnotch.lib.asm.transformer.EntityTransformer.transform(EntityTransformer.java:81)
        at com.evilnotch.lib.asm.transformer.EntityTransformer.transform(EntityTransformer.java:46)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:311)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:183)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.buildEvents(EventSubscriptionTransformer.java:106)
        at net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer.transform(EventSubscriptionTransformer.java:82)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:311)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:183)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.minecraft.item.Item.func_150900_l(Item.java:1625)
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:776)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1602)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:123)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:83)
Transforming: net.minecraft.entity.player.EntityPlayerMP index:3
java.lang.NullPointerException
        at com.evilnotch.lib.asm.transformer.EntityTransformer.patchPlayer(EntityTransformer.java:257)
        at com.evilnotch.lib.asm.transformer.EntityTransformer.transform(EntityTransformer.java:81)
        at com.evilnotch.lib.asm.transformer.EntityTransformer.transform(EntityTransformer.java:46)
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:311)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:183)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:189)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.minecraft.item.Item.func_150900_l(Item.java:1625)
        at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:776)
        at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1602)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:123)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:83)
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:123)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:83)
Caused by: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
        at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
        at java.lang.SecurityManager.checkExit(Unknown Source)
        at java.lang.Runtime.exit(Unknown Source)
        at java.lang.System.exit(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
        
        
**Evil Notch Lib DOESN'T work with any Forge/Bukkit cross-over API's while every-other mod does.**
It causes this error.

**Comment by jredfox** [comment]
No I assure you the Forge/Bukkit cross over APIS including KULDRON will crash with any mod using ASM and not mixins API. If EvilNotchLib is in Minecraft 1.12.2 and you are on the latest version of Evil Notch Lib **And your java version is JRE 8** I may take a look at this but I don't really support minecraft forge mods anymore

**Comment by jredfox** [comment]
If you read the code `java.lang.NullPointerException
at com.evilnotch.lib.asm.transformer.EntityTransformer.patchPlayer(EntityTransformer.java:257)` It's telling you it couldn't get what it was trying to transform. This is caused by the method call `isDedicatedServer` to be non existent in the method it's editing. This is not an issue with EvilNotchLib but of Your weird server software editing the base classes too dramatically

there is no Universal ASM API that when code like that is missing it will still work. I haven't created it yet nor is mixins going to work either no ASM mod would work if the basecode of insertation is plain out missing

**Comment by jredfox** [comment]
A work-around for this is to update to the latest snapshot of evilnotchlib and hope it's fixed as in removed or found a smarter insertion tag
